### PR TITLE
Didn't work OOB after a clone.  Fixed old NuGet dependencies. Changed…

### PR DESCRIPTION
**Pull request by leonmeijer**
… Android SDK to lowest version that ships with VS2015. Renewed expired test certificate (named it Catel).

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Thanks for the PR. We are thin on time and resources, but it's good that the community invests in examples as well. Much appreciated.

**Comment by leonmeijer** [comment]
Although the apps compile, it appears that not everything is working well. No errors, however nothing happens. Will look into it.

**Comment by GeertvanHorrik** [comment]
It's very old code and has never really worked (we had big plans, but Catel features themselves always have a higher prio).

**Comment by leonmeijer** [comment]
Haha right... I see it now, samples are missing the implementation.

**Pull request merged**
